let foo = fn <A: number>(x: A) =>
  if x < 0 { throw "RangeError" } else { throw "BoundsError" };
  
let bar = fn<A: number>(x: A) =>
  try {
    foo(x);
  } catch {
    "RangeError" => 0,
  };
